// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ai.config.* 返回。
 */
export type AiConfigItem = { id: string, provider: string, model: string | null, config_json: string, created_at: string, };
