// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ai.tagging.run 返回。
 */
export type AiRunSummary = { processed: number, written: number, overwritten: number, undo_ids: Array<string>, };
