// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ai.tagging.status 返回。
 */
export type AiTaskItem = { task_id: string, status: string, };
