// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * blueprint.list 返回元素（RFC 0007 / D30）。
 */
export type BlueprintItem = { id: string, name: string, is_default: boolean, schema_version: number, updated_at: string, };
