// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * blueprint.validate 返回（RFC 0007 决策 6；errors 为空 = 有效）。
 */
export type BlueprintValidateResult = { errors: Array<string>, };
