// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * blueprint.template.list 返回元素（RFC 0007 / D30）。
 */
export type BlueprintTemplateItem = { id: string, name: string, description: string | null, schema_version: number, };
