// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BookDefinitionItem } from "./BookDefinitionItem";
import type { BookListItem } from "./BookListItem";
import type { BookSpanItem } from "./BookSpanItem";
import type { BookTableRowItem } from "./BookTableRowItem";

/**
 * 查看器正文的**块**（`book.content` 返回）。
 *
 * **不是 HTML**：见 [`BookSpanItem`] 的安全边界说明。
 *
 * `kind` 取值与各自填充的字段：
 * - `heading`：`level` + `spans`
 * - `paragraph`：`spans`
 * - `image`：`path`（已落盘的绝对路径，供 `convertFileSrc`）
 * - `code_block`：`lang` + `text`
 * - `blockquote`：`quote_kind` + `blocks`
 * - `list`：`ordered` + `start` + `list_items`
 * - `rule`：无附加字段
 * - `table`：`align` + `head` + `rows`
 * - `footnote`：`label` + `blocks`
 * - `definition_list`：`definitions`
 */
export type BookBlockItem = { kind: string, 
/**
 * `heading` 的层级 1–6；其余块为 `null`。
 */
level: number | null, 
/**
 * 行内内容（`heading` / `paragraph`）；其余块为 `null`。
 */
spans: Array<BookSpanItem> | null, 
/**
 * `image` 的已落盘绝对路径（供前端 `convertFileSrc`）；其余为 `null`。
 */
path: string | null, 
/**
 * `code_block` 的语言标记；其余为 `null`。
 */
lang: string | null, 
/**
 * `code_block` 的代码原文（**保留缩进**）；其余为 `null`。
 */
text: string | null, 
/**
 * `blockquote` / `footnote` 内的块；其余为 `null`。
 */
blocks: Array<BookBlockItem> | null, 
/**
 * GFM 告示种类（`note` / `tip` / `important` / `warning` / `caution`）；其余为 `null`。
 */
quote_kind: string | null, 
/**
 * `list` 是否有序；其余为 `null`。
 */
ordered: boolean | null, 
/**
 * `list` 的起始序号；其余为 `null`。
 */
start: number | null, 
/**
 * `list` 的项；其余为 `null`。
 */
list_items: Array<BookListItem> | null, 
/**
 * `table` 的每列对齐（`none` / `left` / `center` / `right`）；其余为 `null`。
 */
align: Array<string> | null, 
/**
 * `table` 的表头单元格；其余为 `null`。
 */
head: Array<Array<BookSpanItem>> | null, 
/**
 * `table` 的表体行；其余为 `null`。
 */
rows: Array<BookTableRowItem> | null, 
/**
 * `footnote` 的标签；其余为 `null`。
 */
label: string | null, 
/**
 * `definition_list` 的各项（术语 + 释义组）；其余为 `null`。
 */
definitions: Array<BookDefinitionItem> | null, };
