// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 一段**行内内容**（`book.content` 返回）。
 *
 * **不是 HTML**：EPUB 的正文是 XHTML、Markdown 可以内嵌 HTML，渲染它们要么走
 * `dangerouslySetInnerHTML`（本项目不接受），要么做一遍受控白名单。后端把白名单
 * **做在解析侧**，前端只拿到这样的纯数据并渲染 React 元素——前端因此没有可注入
 * HTML 的入口（见 `hp-book` 的 `block` / `markdown` 模块文档）。
 */
export type BookSpanItem = { 
/**
 * 文字内容（图片片段里是 **alt 文本**）。
 */
text: string, 
/**
 * 叠加的行内样式（`emphasis` / `strong` / `strikethrough` / `code` /
 * `superscript` / `subscript` / `math` / `footnote`；**已归一化成固定次序**）。
 */
styles: Array<string>, 
/**
 * 链接目标；`null` = 不是链接。
 */
href: string | null, 
/**
 * 图片的**已落盘绝对路径**（供前端 `convertFileSrc`）；`null` = 不是图片。
 */
image: string | null, };
