// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BookBlockItem } from "./BookBlockItem";

/**
 * `book.content` 返回：查看器要显示的正文**一页**。
 *
 * 两种文件走同一个返回体（用户 2026-10-09 口径：txt 与 epub 都在查看器里看）：
 * - `txt` / `md`：一页就是一段连续文本（`text` 非空、`blocks` 为空）；
 * - `epub`：一页就是**一个章节**的块（`blocks` 非空、`text` 为空）。
 */
export type BookContentResult = { 
/**
 * 书的格式：`text`（纯文本）或 `epub`。
 */
format: string, 
/**
 * 纯文本的**编码名**（`UTF-8` / `GBK` / `UTF-16LE` …）；epub 为 `null`。
 *
 * 面板据此提示"这是 GBK 文件"，也让"读出来是乱码"这件事可被用户判断。
 */
encoding: string | null, 
/**
 * 纯文本页的内容；epub 为 `null`。
 */
text: string | null, 
/**
 * epub 章节的块；纯文本为 `null`。
 */
blocks: Array<BookBlockItem> | null, 
/**
 * 下一页游标（纯文本 = 下一个**字符偏移**；epub = 下一个**章节序号**）；
 * `null` = 没有更多（**到末尾不是错误**）。
 */
next_cursor: string | null, 
/**
 * 本页序号（0 起；纯文本恒为 0，epub 是章节序号）。
 */
section: number, 
/**
 * epub 的章节总数；纯文本为 `null`。
 */
section_count: number | null, 
/**
 * 本页标题（epub 的章节标题；纯文本为 `null`）。
 */
title: string | null, 
/**
 * 内容是否因**上限**被截断（用户口径"固定上限"；面板据此提示"仅显示开头"）。
 */
capped: boolean, };
