// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `book.cover` 返回：一个文件的**封面覆盖**（用户自设的颜色或图片）。
 *
 * 用户口径（2026-10-09）："txt 右键可以更换封面颜色或自定义图片"。
 * `kind` 取值：`color`（`value` = `#rrggbb`）/ `image`（`value` = **已落盘**的
 * 绝对路径，供前端 `convertFileSrc`）；两个字段同为 `null` = 这本书没有覆盖，
 * 面板按默认封面渲染（内嵌封面或文字封面）。
 */
export type BookCoverResult = { 
/**
 * `color` / `image`；`null` = 没有覆盖。
 */
kind: string | null, 
/**
 * `color` 为 `#rrggbb`；`image` 为**已落盘**的绝对路径；无覆盖为 `null`。
 */
value: string | null, };
