// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 查看器正文的**块**（`book.content` 返回）。
 *
 * **不是 HTML**：EPUB 的正文是 XHTML，渲染它要么走 `dangerouslySetInnerHTML`
 * （本项目不接受），要么做一遍受控白名单。后端把白名单**做在解析侧**，
 * 前端只拿到这样的纯数据并渲染 React 元素——前端因此没有可注入 HTML 的入口
 * （见 `hp-book` 的 `epub_text` 模块文档）。
 *
 * `kind` 取值：`heading`（`level` + `text`）/ `paragraph`（`text`）/
 * `image`（`path`，已落盘的绝对路径，供 `convertFileSrc`）。
 */
export type BookBlockItem = { kind: string, 
/**
 * `heading` 的层级 1–6；其余块为 `null`。
 */
level: number | null, 
/**
 * `heading` / `paragraph` 的文字；`image` 为 `null`。
 */
text: string | null, 
/**
 * `image` 的已落盘绝对路径（供前端 `convertFileSrc`）；其余为 `null`。
 */
path: string | null, };
