// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BookBlockItem } from "./BookBlockItem";
import type { BookSpanItem } from "./BookSpanItem";

/**
 * **定义列表的一项**（`术语` + 若干条释义）。
 */
export type BookDefinitionItem = { 
/**
 * 术语（行内内容）。
 */
term: Array<BookSpanItem>, 
/**
 * 释义（每条释义是一组块）。
 */
definitions: Array<Array<BookBlockItem>>, };
