// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `book.covers` 返回元素：一个文件的封面覆盖（**只返回真有覆盖的**）。
 *
 * 与 [`BookCoverResult`] 的差别只有一处：这里带 `file_id`（批量结果要靠它对应回条目），
 * 且**两个字段都必然有值**——没有覆盖的文件根本不出现在数组里。
 */
export type BookCoverItem = { 
/**
 * 文件 ID。
 */
file_id: string, 
/**
 * `color` / `image`。
 */
kind: string, 
/**
 * `color` 为 `#rrggbb`；`image` 为**已落盘**的绝对路径（供 `convertFileSrc`）。
 */
value: string, };
