// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BookSpanItem } from "./BookSpanItem";

/**
 * **表格的一行**（`book.content` 返回）。
 */
export type BookTableRowItem = { 
/**
 * 各单元格（每个单元格是一组行内片段）。
 */
cells: Array<Array<BookSpanItem>>, };
