// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BookBlockItem } from "./BookBlockItem";

/**
 * 一个**列表项**（`book.content` 返回）。
 */
export type BookListItem = { 
/**
 * `true` / `false` = 已勾选 / 未勾选（GFM 任务列表）；`null` = 不是任务项。
 */
checked: boolean | null, 
/**
 * 项内的块（列表项可以含多段、嵌套列表、代码块）。
 */
blocks: Array<BookBlockItem>, };
