// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * plugin.discover 返回元素。
 */
export type DiscoveredPlugin = { id: string, name: string, version: string, };
