// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * file.metadata 返回。
 */
export type FileMetadataResult = { id: string, source_id: string, relative_path: string, media_type: string, content_hash: string | null, size: number, mtime: string, verify_status: string, media_info_json: string | null, exif_json: string | null, };
