// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileTagItem } from "./FileTagItem";

/**
 * tag.forFile 返回：人工组（在上）与自动组（在下）分开（D21）。
 */
export type FileTagsResult = { manual: Array<FileTagItem>, auto: Array<FileTagItem>, };
