// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * tag.forFile 返回元素（人工组 / 自动组共用；自动组含置信度）。
 */
export type FileTagItem = { id: string, repo_id: string, name: string, color: string | null, 
/**
 * 自动组置信度；人工组为 `null`。
 */
confidence: number | null, };
