// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * fsops.copy / fsops.move 返回。
 */
export type FsOpsResult = { op_record_id: string, affected: Array<string>, };
