// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * plugin.list 返回元素。
 */
export type PluginItem = { id: string, name: string, version: string, trust_level: string, source_kind: string, source_ref: string | null, runtime_kind: string, installed_at: string, };
