// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * plugin.state 返回。
 */
export type PluginStateItem = { plugin_id: string, repo_id: string, enabled: boolean, grants: Array<string>, };
