// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * plugin.load 返回。
 */
export type PluginLoadItem = { plugin_id: string, repo_id: string, runtime_kind: string, api_version: number, grants: Array<string>, };
