// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * repo.list 返回元素。
 */
export type RepoListItem = { id: string, name: string, repo_db_path: string, created_at: string, last_opened_at: string | null, };
