// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * repo.create / repo.open 返回。
 */
export type RepoSummary = { id: string, name: string, schema_version: number, };
