// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * source.* 返回元素。
 */
export type SourceItem = { id: string, repo_id: string, local_path: string, alias: string | null, parent_source_id: string | null, mounted: boolean, mounted_at: string, };
