// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * tag.list 返回元素。
 */
export type TagItem = { id: string, repo_id: string, name: string, color: string | null, };
