// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * tag.relation.* 返回元素（D22：层级 + 关联，关系图谱数据源）。
 */
export type TagRelationItem = { id: string, repo_id: string, from_tag_id: string, to_tag_id: string, 
/**
 * `hierarchy`（层级）或 `related`（关联）。
 */
relation_kind: string, created_at: string, };
