/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-125157-gefa8b20987-20260622"
#endif /* AVUTIL_FFVERSION_H */
